version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: validate_service.sh
      timeout: 300
      runas: ubuntu
