version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - apt-get update
      - apt-get install nginx -y
      - systemctl start nginx || echo "NGINX might already be running"
  build:
    commands:
      - echo "Build started on $(date)"
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo "Configuring NGINX"
      - nginx -t
      - systemctl restart nginx || echo "NGINX service might already be restarted"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - /var/www/html/index.html
