version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 476114147248.dkr.ecr.us-east-1.amazonaws.com
      - echo Login successful.
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t demoapp:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - echo Tagging the Docker image...
      - docker tag demoapp:$CODEBUILD_RESOLVED_SOURCE_VERSION 476114147248.dkr.ecr.us-east-1.amazonaws.com/demoapp:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 476114147248.dkr.ecr.us-east-1.amazonaws.com/demoapp:latest
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"demoapp","imageUri":"%s"}]' 476114147248.dkr.ecr.us-east-1.amazonaws.com/demoapp:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
