version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Build started on $(date)"
      - git add .
      - git commit -m "First commit"
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - /var/www/html/index.html
